language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
    - composer install --no-dev

script:
    - phpunit --coverage-clover=coverage.clover 2> /dev/null
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false